# Generated by Django 5.0.3 on 2024-05-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
