# Generated by Django 5.0.3 on 2024-05-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0002_house_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="tag",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
