# Generated by Django 5.0.3 on 2024-05-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0003_house_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
