# Generated by Django 5.0.3 on 2024-05-08 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0004_house_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="description",
        ),
    ]
