# Generated by Django 5.0.3 on 2024-05-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0005_remove_house_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meetings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date_scheduled", models.DateTimeField()),
            ],
        ),
    ]
