# Generated by Django 5.0.3 on 2024-05-08 21:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0006_meetings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meetings",
            old_name="subject",
            new_name="house",
        ),
        migrations.RenameField(
            model_name="meetings",
            old_name="message",
            new_name="remarks",
        ),
    ]
