# Generated by Django 5.0.3 on 2024-05-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0007_rename_subject_meetings_house_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("token", models.UUIDField()),
            ],
        ),
    ]
