# Generated by Django 5.0.3 on 2024-06-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apartments", "0010_remove_admin_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("message", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.AlterModelOptions(
            name="admin",
            options={"verbose_name_plural": "Administrators"},
        ),
        migrations.AlterModelOptions(
            name="image",
            options={"verbose_name_plural": "House Images"},
        ),
        migrations.AlterModelOptions(
            name="meetings",
            options={"verbose_name_plural": "Meetings"},
        ),
    ]
