# Generated by Django 5.0.3 on 2024-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apartments",
            "0011_messages_alter_admin_options_alter_image_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="messages",
            name="subject",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
